name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Setup Java JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build web app
      run: npm run build
    
    - name: Setup Capacitor
      run: |
        npm install @capacitor/core @capacitor/cli @capacitor/android
        npx cap init "Gestor Iniciativas" "com.dnd.iniciativas" --web-dir=dist
    
    - name: Add Android platform
      run: npx cap add android
    
    - name: Sync Capacitor
      run: npx cap sync
    
    - name: Grant execute permission for gradlew
      run: chmod +x android/gradlew
    
    - name: Build APK
      working-directory: ./android
      run: ./gradlew assembleDebug
    
    - name: Get APK path
      id: apk-path
      run: |
        echo "APK_PATH=$(find android/app/build/outputs/apk/debug -name '*.apk' | head -n 1)" >> $GITHUB_OUTPUT
    
    - name: Rename APK
      run: |
        APK_FILE=$(find android/app/build/outputs/apk/debug -name '*.apk' | head -n 1)
        DATE=$(date +"%Y%m%d_%H%M%S")
        mv "$APK_FILE" "GestorIniciativas_${DATE}.apk"
        echo "RENAMED_APK=GestorIniciativas_${DATE}.apk" >> $GITHUB_ENV
    
    - name: Upload APK as artifact
      uses: actions/upload-artifact@v3
      with:
        name: gestor-iniciativas-apk
        path: GestorIniciativas_*.apk
        retention-days: 30
    
    - name: Create Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v1.0.${{ github.run_number }}
        name: Release v1.0.${{ github.run_number }}
        body: |
          🎉 Nueva versión del Gestor de Iniciativas D&D
          
          📱 Descarga el APK y instálalo en tu Android
          
          **Características:**
          - ✅ Gestión de iniciativas de combate
          - ✅ Contadores de malus/bonus
          - ✅ Exportación a Excel
          - ✅ Guardado automático
          - ✅ 100% offline
          
          **Instalación:**
          1. Descarga el archivo APK
          2. Activa "Instalar aplicaciones desconocidas"
          3. Abre el APK e instala
        files: GestorIniciativas_*.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
